dashboard/urls.py
from django.urls import path

from dashboard.views.dashboard import DashboardTemplateView

from .views.users.lab_secretaries import (LabSecCreateView, LabSecDetailView,
                                          LabSecListView, LabSecSuspendView)
from .views.users.lab_technicians import (LabTechnicianCreateView,
                                          LabTechnicianDetailView,
                                          LabTechnicianListView,
                                          LabTechnicianSuspendView)
from .views.users.lecturers import (LecturerCreateView, LecturerDetailView,
                                    LecturerListView, LecturerSuspendView)
from .views.users.staff import (StaffCreateView, StaffDetailView,
                                StaffListView, StaffSuspendView)
from .views.users.students import (StudentCreateView, StudentDetailView,
                                   StudentListView, StudentSuspendView)

app_name = "dashboard"

urlpatterns = [
    path('', DashboardTemplateView.as_view(), name='index'),

    # students urls
    path('admin/students/',StudentListView.as_view(),name='students_list'),
    path('admin/students/add',StudentCreateView.as_view(),name='student_add'),
    path('admin/students/<int:pk>/details',StudentDetailView.as_view(),name='student_details'),
    path('admin/students/<int:pk>/suspend',StudentSuspendView.as_view(),name='student_confirm_suspension'),

    # staff urls
    path('admin/staff/',StaffListView.as_view(),name='staff_list'),
    path('admin/staff/add',StaffCreateView.as_view(),name='staff_add'),
    path('admin/staff/<int:pk>/details',StaffDetailView.as_view(),name='staff_details'),
    path('admin/staff/<int:pk>/suspend',StaffSuspendView.as_view(),name='staff_confirm_suspension'),

    # lab technician urls
    path('admin/lab-technicans/', LabTechnicianListView.as_view(),name='lab_technicians_list'),
    path('admin/lab-technicans/add', LabTechnicianCreateView.as_view(),name='lab_technician_add'),
    path('admin/lab-technicans/<int:pk>/details', LabTechnicianDetailView.as_view(),name='lab_technician_details'),
    path('admin/lab-technicans/<int:pk>/suspend', LabTechnicianSuspendView.as_view(),name='lab_technician_confirm_suspension'),

    # lab secretaries
    path('admin/lab-secretaries/',LabSecListView.as_view(),name='lab_secretaries_list'),
    path('admin/lab-secretaries/add',LabSecCreateView.as_view(),name='lab_secretaries_add'),
    path('admin/lab-secretaries/<int:pk>/details',LabSecDetailView.as_view(),name='lab_secretary_details'),
    path('admin/lab-secretaries/<int:pk>/suspend', LabSecSuspendView.as_view(),name='lab_secretary_confirm_suspension'),

    # lecturers
    path('admin/lecturers/',LecturerListView.as_view(),name='lecturers_list'),
    path('admin/lecturers/add',LecturerCreateView.as_view(),name='lecturer_add'),
    path('admin/lecturers/<int:pk>/details',LecturerDetailView.as_view(),name='lecturer_details'),
    path('admin/lecturers/<int:pk>/suspend', LecturerSuspendView.as_view(),name='lecturer_confirm_suspension'),
]

equipment/urls.py
from django.urls import path

from .views.allocations import (AllocateToLecturerView, AllocateToStudentView,
                                AllocationCreateView, AllocationDetailView,
                                AllocationListView, AllocationUpdateView,
                                allocate_equipment, allocation_mark_as_damaged,
                                allocation_mark_as_fixed,
                                allocation_mark_as_lost,
                                allocation_mark_as_replaced, mark_as_returned,
                                unallocate_equipment)
from .views.batches import (BatchCreateView, BatchDetailView, BatchListView,
                            BatchUpdateView)
from .views.categories import (CategoryCreateView, CategoryDeleteView,
                               CategoryDetailView, CategoryListView,
                               CategoryUpdateView)
from .views.equipment import (EquipmentCreateView, EquipmentDeleteView,
                              EquipmentDetailView, EquipmentListView,
                              EquipmentUpdateView, mark_as_damaged,
                              mark_as_found, mark_as_lost, mark_as_out_service,
                              mark_as_working)
from .views.storage_units import (StorageUnitCreateView, StorageUnitDetailView,
                                  StorageUnitListView, StorageUnitUpdateView)
from .views.suppliers import (SupplierCreateView, SupplierDetailView,
                              SupplierListView, SupplierUpdateView)

app_name = "equipment"


urlpatterns = [
    # equipment category urls
    path('categories/',CategoryListView.as_view(),name="categories_list"),
    path('categories/add',CategoryCreateView.as_view(),name="category_add"),
    path('categories/<int:pk>/details',CategoryDetailView.as_view(),name="category_details"),
    path('categories/<int:pk>/edit',CategoryUpdateView.as_view(),name="category_edit"),
    path('categories/<int:pk>/delete',CategoryDeleteView.as_view(),name="category_delete"),

    # equipment batches urls
    path('batches/',BatchListView.as_view(),name="batch_list"),
    path('batches/add',BatchCreateView.as_view(),name="batch_add"),
    path('batches/<int:pk>/details',BatchDetailView.as_view(),name="batch_details"),
    path('batches/<int:pk>/edit',BatchUpdateView.as_view(),name="batch_edit"),

    #  equipment urls
    path('equipment/',EquipmentListView.as_view(),name="equipment_list"),
    path('equipment/add',EquipmentCreateView.as_view(),name="equipment_add"),
    path('equipment/<int:pk>/details',EquipmentDetailView.as_view(),name="equipment_details"),
    path('equipment/<int:pk>/edit',EquipmentUpdateView.as_view(),name="equipment_edit"),
    path('equipment/<int:pk>/delete',EquipmentDeleteView.as_view(),name="equipment_delete"),
    path('equipment/<int:pk>/mark-as-damaged/',mark_as_damaged,name="equipment_damaged_action"),
    path('equipment/<int:pk>/mark-as-working/',mark_as_working,name="equipment_working_action"),
    path('equipment/<int:pk>/mark-as-out-of-service/',mark_as_out_service,name="equipment_out_of_service_action"),
    path('equipment/<int:pk>/mark-as-lost/',mark_as_lost,name="equipment_lost_action"),
    path('equipment/<int:pk>/mark-as-found/',mark_as_found,name="equipment_found_action"),

    # supplier urls
    path('suppliers/', SupplierListView.as_view(), name='supplier_list'),
    path('suppliers/add/', SupplierCreateView.as_view(), name='supplier_add'),
    path('suppliers/<int:pk>/details/', SupplierDetailView.as_view(), name='supplier_details'),
    path('suppliers/<int:pk>/edit/', SupplierUpdateView.as_view(), name='supplier_edit'),

    # storage units
    path('storage-units/',StorageUnitListView.as_view(),name="storage_units_list"),
    path('storage-units/add',StorageUnitCreateView.as_view(),name="storage_unit_add"),
    path('storage-units/<int:pk>/details',StorageUnitDetailView.as_view(),name="storage_unit_details"),
    path('storage-units/<int:pk>/edit',StorageUnitUpdateView.as_view(),name="storage_unit_edit"),

    # allocations
    path('allocations/',AllocationListView.as_view(),name="all_allocations"),
    path('allocations/new/',AllocationCreateView.as_view(),name="new_allocation"),
    path('allocations/<int:pk>/details/',AllocationDetailView.as_view(),name="allocation_details"),
    path('allocations/<int:pk>/edit',AllocationUpdateView.as_view(),name="allocation_edit"),
    path('allocations/<int:pk>/mark-as-returned/', mark_as_returned, name="allocation_return_action"),
    path('allocations/<int:pk>/mark-as-damaged/', allocation_mark_as_damaged, name="allocation_damaged_action"),
    path('allocations/<int:pk>/mark-as-fixed/', allocation_mark_as_fixed, name="allocation_fixed_action"),
    path('allocations/<int:pk>/mark-as-lost/', allocation_mark_as_lost, name="allocation_lost_action"),
    path('allocations/<int:pk>/mark-as-replaced/', allocation_mark_as_replaced, name="allocation_replaced_action"),
    path('allocations/<int:pk>/allocate-to-student/', AllocateToStudentView.as_view(), name="allocate_to_student"),
    path('allocations/<int:pk>/allocate-to-lecturer/', AllocateToLecturerView.as_view(), name="allocate_to_lecturer"),
    path('allocations/<int:pk>/allocate/<int:user_pk>/', allocate_equipment, name="allocate_equipment_action"),
    path('allocations/<int:pk>/unallocate/<int:user_pk>/', unallocate_equipment, name="unallocate_equipment_action"),
]

scitlab/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView
from users.views.base import logout_user, login_redirect, LoginUserView, IndexTemplateView


urlpatterns = [
    # path('', IndexTemplateView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('accounts/',include('allauth.urls')),
    path('accounts/logout', logout_user, name='logout'),
    path('', LoginUserView.as_view(template_name='account/login.html'), name='login'),
    # path('', LoginView.as_view(template_name='account/login.html'),name='index'),
    path('accounts/login-redirect/', login_redirect, name='login_redirect'),
    path('dashboard/',include('dashboard.urls',namespace='dashboard')),
    path('users/',include('users.urls',namespace='users')),
    path('schools/',include('schools.urls',namespace='schools')),
    path('equipment/',include('equipment.urls',namespace='equipment')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path

from users.views.admin_actions import suspend_user, unsuspend_user
from users.views.lab_sec import LabSecDashboardView
from users.views.lab_technicians.equipment import (EquipmentCreateView,
                                                   EquipmentDetailView,
                                                   EquipmentListView,
                                                   EquipmentUpdateView,
                                                   StorageUnitDetailView,
                                                   StorageUnitListView,
                                                   StorageUnitCreateView)
from users.views.lab_technicians.index import LabTechnicianDashboardView
from users.views.students import StudentorLecturerDashboardView
from users.views.users.allocations import (AllocationDetailView,
                                           AllocationListView)

from .views.lab_technicians.allocations import (AllocateToLecturerView,
                                                AllocateToStudentView,
                                                AllocationCreateView,
                                                allocate_equipment)
from .views.lab_technicians.categories import (CategoryCreateView,
                                               CategoryDeleteView,
                                               CategoryDetailView,
                                               CategoryListView,
                                               CategoryUpdateView)
from .views.lab_technicians.lecturers import (LecturerDetailView,
                                              LecturerListView)
from .views.lab_technicians.students import StudentDetailView, StudentListView
from .views.lecturers import LecturerDashboardView
from .views.users.base import UserDetailView, UserProfileUpdateView

app_name = "users"

urlpatterns = [
    # lab technician url
    path('lab-technicians-dashboard/', LabTechnicianDashboardView.as_view(),
         name='lab_technicians_dashboard_index'),
    path('equipment/all/', EquipmentListView.as_view(), name="equipment_list"),
    path('equipment/add/', EquipmentCreateView.as_view(), name="equipment_add"),
    path('equipment/<int:pk>/details',
         EquipmentDetailView.as_view(), name="equipment_details"),
    path('equipment/<int:pk>/edit',
         EquipmentUpdateView.as_view(), name="equipment_edit"),
    path('storage-units/add', StorageUnitCreateView.as_view(),
         name="storage_unit_add"),
    path('storage-units/', StorageUnitListView.as_view(),
         name="storage_units_list"),
    path('storage-units/<int:pk>/details',
         StorageUnitDetailView.as_view(), name="storage_unit_details"),
    path('lab-technicians-dashboard/lecturers/all',
         LecturerListView.as_view(), name="lecturer_list"),
    path('lab-technicians-dashboard/lecturers/<int:pk>/details',
         LecturerDetailView.as_view(), name="lecturer_details"),
    path('lab-technicians-dashboard/students/all',
         StudentListView.as_view(), name="students_list"),
    path('lab-technicians-dashboard/students/<int:pk>/details',
         StudentDetailView.as_view(), name="student_details"),

    # allocations urls
    path('allocations/new/', AllocationCreateView.as_view(), name="new_allocation"),
    # lab secretary urls
    path('lab-secretaries-dashboard/', LabSecDashboardView.as_view(),
         name='lab_sec_dashboard_index'),

    # student dashboard
    path('student-dashboard/', StudentorLecturerDashboardView.as_view(),
         name="student_dashboard_index"),

    # lecturer
    path('lecturer-dashboard/', LecturerDashboardView.as_view(),
         name="lecturer_dashboard_index"),

    path('users/<int:pk>/suspend_user', suspend_user, name="user_suspend_action"),
    path('admin/admin/users/<int:pk>/unsuspend_user',
         unsuspend_user, name="user_unsuspend_action"),
    path('my-profile/', UserDetailView.as_view(), name="user_profile"),
    path('<int:pk>/profile-update/',
         UserProfileUpdateView.as_view(), name="profile_update"),

    # Allocation urls
    path('allocations/all/', AllocationListView.as_view(), name="allocations_list"),
    path('allocations/<int:pk>/details/',
         AllocationDetailView.as_view(), name="allocation_details"),
    path('allocations/<int:pk>/allocate-to-student/',
         AllocateToStudentView.as_view(), name="allocate_to_student"),
    path('allocations/<int:pk>/allocate-to-lecturer/',
         AllocateToLecturerView.as_view(), name="allocate_to_lecturer"),
    path('allocations/<int:pk>/allocate/<int:user_pk>/',
         allocate_equipment, name="allocate_equipment_action"),

    path('categories/', CategoryListView.as_view(), name="categories_list"),
    path('categories/add', CategoryCreateView.as_view(), name="category_add"),
    path('categories/<int:pk>/details',
         CategoryDetailView.as_view(), name="category_details"),
    path('categories/<int:pk>/edit',
         CategoryUpdateView.as_view(), name="category_edit"),
    path('categories/<int:pk>/delete',
         CategoryDeleteView.as_view(), name="category_delete"),
]

equipment/views.py
from django.shortcuts import render
from .models import Category, Equipment
from django.views.generic import CreateView, ListView, DetailView, UpdateView
from dashboard.views.dashboard import DashboardView



class CategoryCreateView(DashboardView, CreateView):
    model = Category
    fields = ("name")
    template_name = 'equipment/categories/add.html'


class CategoryListView(DashboardView, ListView):
    model = Category
    template_name = 'equipment/categories/list.html'
    context_object_name = 'categories'


class CategoryDetailView(DashboardView, DetailView):
    model = Category
    template_name = 'equipment/categories/details.html'
    context_object_name = 'category'

equipment/views/batches.py
from django.shortcuts import render
from django.contrib import messages
from ..models import Batch, Equipment
from django.views.generic import CreateView, ListView, DetailView, UpdateView
from dashboard.views.dashboard import DashboardView
from django.urls import reverse_lazy



class BatchCreateView(DashboardView, CreateView):
    model = Batch
    fields = ('category','supplier','serial_no','school','equipment_quantities')
    template_name = 'dashboard/equipment/batches/add.html'

    def get_success_url(self):
        messages.success(self.request,"Batch Added Successfully")
        return reverse_lazy('equipment:batch_details', kwargs={'pk':self.object.pk})


class BatchListView(DashboardView, ListView):
    model = Batch
    template_name = 'dashboard/equipment/batches/list.html'
    context_object_name = 'batches'


class BatchDetailView(DashboardView, DetailView):
    model = Batch
    template_name = 'dashboard/equipment/batches/details.html'
    context_object_name = 'batch'


class BatchUpdateView(DashboardView, UpdateView):
    model = Batch
    template_name = 'dashboard/equipment/batches/edit.html'
    fields = ('category','supplier', 'serial_no','school','equipment_quantities')

    def get_success_url(self):
        messages.success(self.request,"Batch Updated")
        return reverse_lazy('equipment:batch_details', kwargs={'pk':self.object.pk})

templates/dashboard/equipment/allocations/add.html
{% extends 'base.html' %}
{% block title %}
    Add New Equipment Allocation
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="card shadow-sm">
            <div class="card-body">
                <h3 class="text-center py-3">Allocate Equipment</h3>
                <div class="col-md-10 mx-auto">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'partials/form.html' %}
                        <div class="py-3 text-center">
                            <button class="btn btn-primary">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/dashboard/equipment/allocations/allocate-lecturer.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
All Students
{% endblock %}


{% block styles %}
<link href="{% static 'css/data-tables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="col-xl-12 col-md-12">
    <div class="card Recent-users">
        <div class="card-header">
            <h5>Allocate equipment To Lecturer </h5>
        </div>
        <div class="card-block px-0 py-3">
            <div class="table-responsive">
                <table class="table" id="data-table">
                    <thead>
                        <tr>
                            <th> Full Name </th>
                            <th> Gender </th>
                            <th> Contact </th>
                            <th> Staff ID </th>
                            <th> Department </th>
                            <th> Status </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for user in users %}
                        <tr>
                            <td>{{ user.get_full_name }}</td>
                            <td>{{ user.gender }}</td>
                            <td>{{ user.phone_number }}</td>
                            <td>{{ user.staff_id }}</td>
                            <td>{{ user.department.name }}</td>
                            {% if user.is_active %}
                            <td><span class="badge badge-pill badge-success">Active</span></td>
                            {% else %}
                            <td><span class="badge badge-pill badge-danger">Suspended</span></td>
                            {% endif %}
                            {% if request.user.user_type == 'Staff' %}
                            <td><a href=" {% url 'equipment:allocate_equipment_action' pk=allocation.pk user_pk=user.pk  %} " class="label theme-bg3 text-white f-12">Allocate</a></td>
                            {% elif request.user.user_type == 'Lab_Tech' %}
                            <td><a href=" {% url 'users:allocate_equipment_action' pk=allocation.pk user_pk=user.pk  %} " class="label theme-bg3 text-white f-12">Allocate</a></td>
                            {% endif %}
                            
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock  %}

{% block scripts %}
<script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script>
<script>
    $('#data-table').DataTable();
</script>
{% endblock %}

templates/dashboard/equipment/allocations/allocate-student.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
All Students
{% endblock %}


{% block styles %}
<link href="{% static 'css/data-tables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="col-xl-12 col-md-12">
    <div class="card Recent-users">
        <div class="card-header">
            <h5>Allocate equipment To Student </h5>
        </div>
        <div class="card-block px-0 py-3">
            <div class="table-responsive">
                <table class="table" id="data-table">
                    <thead>
                        <tr>
                            <th> Full Name </th>
                            <th> Gender </th>
                            <th> Contact </th>
                            <th> Course </th>
                            <th> Status </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for user in users %}
                        <tr>
                            <td>{{ user.get_full_name }}</td>
                            <td>{{ user.gender }}</td>
                            <td>{{ user.phone_number }}</td>
                            <td>{{ user.course }}</td>
                            {% if user.is_active %}
                            <td><span class="badge badge-pill badge-success">Active</span></td>
                            {% else %}
                            <td><span class="badge badge-pill badge-danger">Suspended</span></td>
                            {% endif %}
                            {% if request.user.user_type == 'Staff' %}
                            <td><a href=" {% url 'equipment:allocate_equipment_action' pk=allocation.pk user_pk=user.pk  %} " class="label theme-bg3 text-white f-12">Allocate</a></td>
                            {% elif request.user.user_type == 'Lab_Tech' %}
                            <td><a href=" {% url 'users:allocate_equipment_action' pk=allocation.pk user_pk=user.pk  %} " class="label theme-bg3 text-white f-12">Allocate</a></td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock  %}

{% block scripts %}
<script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script>
<script>
    $('#data-table').DataTable();
</script>
{% endblock %}

templates/dashboard/equipment/allocations/details.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
allocation Details
{% endblock %}


{% block styles %}
<link href="{% static 'css/data-tables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12 ">
                        <div class="m-3 p-3 shadow-sm">
                            <h3 class="text-center py-3">Allocation Details</h3>
                            <div class="table-responsive">
                                <table class="table table-striped text-center">
                                    <tbody>
                                        <tr>
                                            <th>Allocated To.</th>
                                            {% if allocation.allocated_to.user_type == 'Student' %}
                                            <td> <a href="{% url 'dashboard:student_details' allocation.allocated_to.id %}"> {{ allocation.allocated_to.get_full_name }} </a> </td>
                                            {% elif allocation.allocated_to.user_type == 'Lecturer' %}
                                            <td> <a href="{% url 'dashboard:lecturer_details' allocation.allocated_to.id %}"> {{ allocation.allocated_to.get_full_name }} </a> </td>
                                            {% elif allocation.allocated_to.user_type == 'Lab_Tech' %}
                                            <td> <a href="{% url 'dashboard:lab_technician_details' allocation.allocated_to.id %}"> {{ allocation.allocated_to.get_full_name }} </a> </td>
                                            {% endif %}
                                        </tr>
                                        <tr>
                                            <th>Equipment</th>
                                            <td><a href="{% url 'equipment:equipment_details' allocation.equipment.id %}">{{ allocation.equipment.name }} - {{ allocation.equipment.serial_no }} </a></td>
                                        </tr>
                                        <tr>
                                            <th>Added On</th>
                                            <td>{{ allocation.created_on }}</td>
                                        </tr>
                                        <tr>
                                            <th>Allocated By</th>
                                            <td> <a href="{% url 'dashboard:lab_technician_details' allocation.allocated_by.id %}"> {{ allocation.allocated_by }} </a> </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="text-center">
                        {% if not allocation.is_returned %}
                            <a href="{% url 'equipment:allocation_return_action' pk=allocation.pk %}" class="mx-1">
                                <button class="btn btn-md  btn-success">Mark as Returned</button>
                            </a>
                        {% endif %}
                            <a href="{% url 'equipment:allocation_edit' allocation.pk %}" class="mx-1">
                                <button class="btn btn-md btn-primary">Edit</button>
                            </a>
                            {% if not allocation.equipment.is_damaged %}
                            <a href="{% url 'equipment:allocation_damaged_action' pk=allocation.pk %}" class="mx-1">
                                <button class="btn btn-md  btn-warning">Mark as damaged</button>
                            </a>
                            {% else%}
                            <a href="{% url 'equipment:allocation_damaged_action' pk=allocation.pk %}" class="mx-1">
                                <button class="btn btn-md  btn-info">Mark as Replaced</button>
                            </a>
                            {% endif %}
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>



    </div>
</div>
    
    </div>
</div>

{% endblock  %}

{% block scripts %}
<script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script>
<script>
    $('#data-table').DataTable();
</script>
{% endblock %}

templates/dashboard/equipment/allocations/edit.html
{% extends 'base.html' %}
{% block title %}
    Edit Equipment Allocation
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="card shadow-sm">
            <div class="card-body">
                <h3 class="text-center py-3">Edit Equipment Allocation</h3>
                <div class="col-md-10 mx-auto">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'partials/form.html' %}
                        <div class="py-3 text-center">
                            <button class="btn btn-primary">Save Changes</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/dashboard/equipment/allocations/list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
All Equipment allocations
{% endblock %}


{% block styles %}
<link href="{% static 'css/data-tables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="col-xl-12 col-md-12">
    <div class="card Recent-allocations">
        <div class="card-header">
            <h5>All allocations</h5>
        </div>
        <div class="card-block px-0 py-3">
            <div class="table-responsive">
                <table class="table" id="data-table">
                    <div class="float-right">
                        <a href="{% url 'equipment:new_allocation' %}" class="label theme-bg2 text-white f-12">Add allocation</a>
                    </div>
                    <thead>
                        <tr>
                            <th>Allocated To.</th>
                            <th>Equipment</th>
                            <th>Serial No</th>
                            <th>Allocated By</th>
                            <th>Status</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for allocation in allocations %}
                        <tr>
                            <td>{{ allocation.allocated_to.get_full_name }}</td>
                            <td>{{ allocation.equipment.name }}</td>
                            <td>{{ allocation.equipment.serial_no }}</td>
                            <td>{{ allocation.allocated_by.get_full_name }}</td>
                            {% if allocation.is_returned %}
                            <td><span class="badge badge-pill badge-success">Returned</span></td>
                            {% else %}
                            <td><span class="badge badge-pill badge-danger">Unreturned</span></td>
                            {% endif %}
                            <td>{{ allocation.created_on }}</td>
                            <td><a href=" {% url 'equipment:allocation_details' allocation.pk %} " class="label theme-bg2 text-white f-12">View</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock  %}

{% block scripts %}
<script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script>
<script>
    $('#data-table').DataTable();
</script>
{% endblock %}