dashboard/urls.py
from django.urls import path

from dashboard.views.dashboard import DashboardTemplateView

from .views.users.lab_secretaries import (LabSecCreateView, LabSecDetailView,
                                          LabSecListView, LabSecSuspendView)
from .views.users.lab_technicians import (LabTechnicianCreateView,
                                          LabTechnicianDetailView,
                                          LabTechnicianListView,
                                          LabTechnicianSuspendView)
from .views.users.lecturers import (LecturerCreateView, LecturerDetailView,
                                    LecturerListView, LecturerSuspendView)
from .views.users.staff import (StaffCreateView, StaffDetailView,
                                StaffListView, StaffSuspendView)
from .views.users.students import (StudentCreateView, StudentDetailView,
                                   StudentListView, StudentSuspendView)

app_name = "dashboard"

urlpatterns = [
    path('', DashboardTemplateView.as_view(), name='index'),

    # students urls
    path('admin/students/',StudentListView.as_view(),name='students_list'),
    path('admin/students/add',StudentCreateView.as_view(),name='student_add'),
    path('admin/students/<int:pk>/details',StudentDetailView.as_view(),name='student_details'),
    path('admin/students/<int:pk>/suspend',StudentSuspendView.as_view(),name='student_confirm_suspension'),

    # staff urls
    path('admin/staff/',StaffListView.as_view(),name='staff_list'),
    path('admin/staff/add',StaffCreateView.as_view(),name='staff_add'),
    path('admin/staff/<int:pk>/details',StaffDetailView.as_view(),name='staff_details'),
    path('admin/staff/<int:pk>/suspend',StaffSuspendView.as_view(),name='staff_confirm_suspension'),

    # lab technician urls
    path('admin/lab-technicans/', LabTechnicianListView.as_view(),name='lab_technicians_list'),
    path('admin/lab-technicans/add', LabTechnicianCreateView.as_view(),name='lab_technician_add'),
    path('admin/lab-technicans/<int:pk>/details', LabTechnicianDetailView.as_view(),name='lab_technician_details'),
    path('admin/lab-technicans/<int:pk>/suspend', LabTechnicianSuspendView.as_view(),name='lab_technician_confirm_suspension'),

    # lab secretaries
    path('admin/lab-secretaries/',LabSecListView.as_view(),name='lab_secretaries_list'),
    path('admin/lab-secretaries/add',LabSecCreateView.as_view(),name='lab_secretaries_add'),
    path('admin/lab-secretaries/<int:pk>/details',LabSecDetailView.as_view(),name='lab_secretary_details'),
    path('admin/lab-secretaries/<int:pk>/suspend', LabSecSuspendView.as_view(),name='lab_secretary_confirm_suspension'),

    # lecturers
    path('admin/lecturers/',LecturerListView.as_view(),name='lecturers_list'),
    path('admin/lecturers/add',LecturerCreateView.as_view(),name='lecturer_add'),
    path('admin/lecturers/<int:pk>/details',LecturerDetailView.as_view(),name='lecturer_details'),
    path('admin/lecturers/<int:pk>/suspend', LecturerSuspendView.as_view(),name='lecturer_confirm_suspension'),
]

scitlab/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView
from users.views.base import logout_user, login_redirect, LoginUserView, IndexTemplateView


urlpatterns = [
    # path('', IndexTemplateView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('accounts/',include('allauth.urls')),
    path('accounts/logout', logout_user, name='logout'),
    path('', LoginUserView.as_view(template_name='account/login.html'), name='login'),
    # path('', LoginView.as_view(template_name='account/login.html'),name='index'),
    path('accounts/login-redirect/', login_redirect, name='login_redirect'),
    path('dashboard/',include('dashboard.urls',namespace='dashboard')),
    path('users/',include('users.urls',namespace='users')),
    path('schools/',include('schools.urls',namespace='schools')),
    path('equipment/',include('equipment.urls',namespace='equipment')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path

from users.views.admin_actions import suspend_user, unsuspend_user
from users.views.lab_sec import LabSecDashboardView
from users.views.lab_technicians.equipment import (EquipmentCreateView,
                                                   EquipmentDetailView,
                                                   EquipmentListView,
                                                   EquipmentUpdateView,
                                                   StorageUnitDetailView,
                                                   StorageUnitListView,
                                                   StorageUnitCreateView)
from users.views.lab_technicians.index import LabTechnicianDashboardView
from users.views.students import StudentorLecturerDashboardView
from users.views.users.allocations import (AllocationDetailView,
                                           AllocationListView)

from .views.lab_technicians.allocations import (AllocateToLecturerView,
                                                AllocateToStudentView,
                                                AllocationCreateView,
                                                allocate_equipment)
from .views.lab_technicians.categories import (CategoryCreateView,
                                               CategoryDeleteView,
                                               CategoryDetailView,
                                               CategoryListView,
                                               CategoryUpdateView)
from .views.lab_technicians.lecturers import (LecturerDetailView,
                                              LecturerListView)
from .views.lab_technicians.students import StudentDetailView, StudentListView
from .views.lecturers import LecturerDashboardView
from .views.users.base import UserDetailView, UserProfileUpdateView

app_name = "users"

urlpatterns = [
    # lab technician url
    path('lab-technicians-dashboard/', LabTechnicianDashboardView.as_view(),
         name='lab_technicians_dashboard_index'),
    path('equipment/all/', EquipmentListView.as_view(), name="equipment_list"),
    path('equipment/add/', EquipmentCreateView.as_view(), name="equipment_add"),
    path('equipment/<int:pk>/details',
         EquipmentDetailView.as_view(), name="equipment_details"),
    path('equipment/<int:pk>/edit',
         EquipmentUpdateView.as_view(), name="equipment_edit"),
    path('storage-units/add', StorageUnitCreateView.as_view(),
         name="storage_unit_add"),
    path('storage-units/', StorageUnitListView.as_view(),
         name="storage_units_list"),
    path('storage-units/<int:pk>/details',
         StorageUnitDetailView.as_view(), name="storage_unit_details"),
    path('lab-technicians-dashboard/lecturers/all',
         LecturerListView.as_view(), name="lecturer_list"),
    path('lab-technicians-dashboard/lecturers/<int:pk>/details',
         LecturerDetailView.as_view(), name="lecturer_details"),
    path('lab-technicians-dashboard/students/all',
         StudentListView.as_view(), name="students_list"),
    path('lab-technicians-dashboard/students/<int:pk>/details',
         StudentDetailView.as_view(), name="student_details"),

    # allocations urls
    path('allocations/new/', AllocationCreateView.as_view(), name="new_allocation"),
    # lab secretary urls
    path('lab-secretaries-dashboard/', LabSecDashboardView.as_view(),
         name='lab_sec_dashboard_index'),

    # student dashboard
    path('student-dashboard/', StudentorLecturerDashboardView.as_view(),
         name="student_dashboard_index"),

    # lecturer
    path('lecturer-dashboard/', LecturerDashboardView.as_view(),
         name="lecturer_dashboard_index"),

    path('users/<int:pk>/suspend_user', suspend_user, name="user_suspend_action"),
    path('admin/admin/users/<int:pk>/unsuspend_user',
         unsuspend_user, name="user_unsuspend_action"),
    path('my-profile/', UserDetailView.as_view(), name="user_profile"),
    path('<int:pk>/profile-update/',
         UserProfileUpdateView.as_view(), name="profile_update"),

    # Allocation urls
    path('allocations/all/', AllocationListView.as_view(), name="allocations_list"),
    path('allocations/<int:pk>/details/',
         AllocationDetailView.as_view(), name="allocation_details"),
    path('allocations/<int:pk>/allocate-to-student/',
         AllocateToStudentView.as_view(), name="allocate_to_student"),
    path('allocations/<int:pk>/allocate-to-lecturer/',
         AllocateToLecturerView.as_view(), name="allocate_to_lecturer"),
    path('allocations/<int:pk>/allocate/<int:user_pk>/',
         allocate_equipment, name="allocate_equipment_action"),

    path('categories/', CategoryListView.as_view(), name="categories_list"),
    path('categories/add', CategoryCreateView.as_view(), name="category_add"),
    path('categories/<int:pk>/details',
         CategoryDetailView.as_view(), name="category_details"),
    path('categories/<int:pk>/edit',
         CategoryUpdateView.as_view(), name="category_edit"),
    path('categories/<int:pk>/delete',
         CategoryDeleteView.as_view(), name="category_delete"),
]

users/models.py
from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models
from django.utils.translation import ugettext_lazy as _
from schools.models import Course, Department, Lab


class UserAccountManager(UserManager):
    def create_user(self, username=None, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, email, password, **extra_fields)

    def create_superuser(self, username=None, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff status.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Super user must have is_superuser status')

        return self._create_user(email, email, password, **extra_fields)

GENDER_CHOICES = (
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Other', 'Other'),
    )
MEMBERSHIP_CHOICES = (
    ('Lab_Tech', 'Lab Technician'),
    ('Lab_Sec', 'Lab Secretary'),
    ('Lecturer', 'Lecturer'),
    ('Student', 'Student'),
    ('Staff', 'Staff'),
)

YEAR_OF_STUDY_CHOICES = (
    ('Select One', 'Select One'),
    ('1st Year', 'First Year'),
    ('2nd Year', 'Second Year'),
    ('3rd Year', 'Third Year'),
    ('4th Year', 'Fourth Year'),
    ('5th Year', 'Fifth Year'),
    ('6th Year', 'Sixth Year'),
)
class UserAccount(AbstractUser):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    photo = models.ImageField(upload_to='media/profiles', null=True)
    phone_number = models.CharField(max_length=50)
    user_type = models.CharField(max_length=30,choices=MEMBERSHIP_CHOICES,default='Staff')
    gender = models.CharField(max_length=20, choices=GENDER_CHOICES)
    course = models.ForeignKey(Course,on_delete=models.PROTECT,null=True,blank=True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, null=True, blank=True, related_name='users')
    year_of_study = models.CharField(max_length=30, choices=YEAR_OF_STUDY_CHOICES,default="Select One",blank=True,null=True)
    staff_id = models.CharField(max_length=50, null=True,blank=True)
    registration_no = models.CharField(max_length=50, null=True, blank=True, verbose_name='Registration Number')
    lab = models.ForeignKey(Lab, on_delete=models.CASCADE, related_name='users', null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'phone_number',]

    objects = UserAccountManager()

    def __str__(self):
        return f"{self.get_full_name()}"

users/views/forms.py
from django import forms

from equipment.models import Allocation, Equipment, StorageUnit


class AllocationCreateForm(forms.ModelForm):
    equipment = forms.ModelChoiceField(queryset=Equipment.objects.filter(
        is_allocated=False, has_exceeded_shelf_life=False, is_lost=False, is_damaged=False))

    class Meta:
        model = Allocation
        fields = ('equipment', 'allocating_to')


class EquipmentCreationForm(forms.ModelForm):
    # def __init__(self, request, *args, **kwargs):
    #         super(EquipmentCreationForm, self).__init__(request, *args, **kwargs)
    #         self.fields['storage_unit'].queryset = StorageUnit.objects.filter(lab=request.user.lab)

    class Meta:
        model = Equipment
        fields = ('name', 'serial_no', 'category', 'storage_unit', 'price')

users/views/admin_actions.py
from django.shortcuts import get_object_or_404, redirect
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic import DetailView

from ..models import UserAccount


# logic for suspending users and redirection based on user type
def suspend_user(request, pk):
    user = get_object_or_404(UserAccount, pk=pk)
    user.is_active = not user.is_active
    user.save()

    if(user.user_type == 'Lab_Tech'):
        messages.success(request,"User suspended")
        return redirect("dashboard:lab_technician_details", pk=pk)
    elif(user.user_type == 'Lab_Sec'):
        messages.success(request,"User suspended")
        return redirect("dashboard:lab_secretaries_details", pk=pk)
    elif(user.user_type == 'Staff'):
        messages.success(request,"User suspended")
        return redirect("dashboard:staff_details", pk=pk)
    elif(user.user_type == 'Student'):
        messages.success(request,"User suspended")
        return redirect("dashboard:student_details", pk=pk)
    elif(user.user_type == 'Lecturer'):
        messages.success(request,"User suspended")
        return redirect("dashboard:lecturer_details", pk=pk)

# logic for unsuspending users and redirection
def unsuspend_user(request,pk):
    user = get_object_or_404(UserAccount, pk=pk)
    user.is_active = True
    user.save()

    if(user.user_type == 'Lab_Tech'):
        messages.success(request,"User activated")
        return redirect("dashboard:lab_technician_details", pk=pk)
    elif(user.user_type == 'Lab_Sec'):
        messages.success(request,"User activated")
        return redirect("dashboard:lab_secretaries_details", pk=pk)
    elif(user.user_type == 'Staff'):
        messages.success(request,"User activated")
        return redirect("dashboard:staff_details", pk=pk)
    elif(user.user_type == 'Student'):
        messages.success(request,"User activated")
        return redirect("dashboard:student_details", pk=pk)
    elif(user.user_type == 'Lecturer'):
        messages.success(request,"User activated")
        return redirect("dashboard:lecturer_details", pk=pk)

users/views/base.py
from allauth.account.views import LoginView
from django.views.generic import TemplateView,UpdateView
from django.contrib.auth import logout,login
from django.shortcuts import redirect,render
from django.contrib import messages
from django.contrib.auth import authenticate
from django.urls import reverse_lazy

class IndexTemplateView(TemplateView):
    template_name = 'account/login.html'

def logout_user(request):
    logout(request)
    return redirect('login')

# handle redirect based on user role
def login_redirect(request):
    if request.user.user_type == 'Student':
        return redirect('users:student_dashboard_index')
    elif request.user.user_type == 'Lab_Tech':
        return redirect('users:lab_technicians_dashboard_index')
    elif request.user.user_type == 'Lecturer':
        return redirect('users:lecturer_dashboard_index')
    elif request.user.is_staff:
        return redirect('dashboard:index')


class LoginUserView(LoginView):

    def get_success_url(self):
        return reverse_lazy('login_redirect')

def register_redirect(request):
    if request.user.user_type == 'Student':
        return redirect('users:student_dashboard_index')
    elif request.user.user_type == 'Lab_Tech':
        return redirect('users:lab_technician_dashboard_index')
    elif request.user.user_type == 'Lab_Sec':
        return redirect('users:lab_sec_dashboard_index')
    elif request.user.user_type == 'Lecturer':
        return redirect('users:lecturer_dashboard_index')
    elif request.user.is_staff and request.user.user_type == 'Staff':
        return redirect('dashboard:index')


class RegisterUserView(UpdateView):
    def get_success_url(self):
        return reverse_lazy('register_redirect')

users/views/lab_sec.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import CreateView, UpdateView, ListView, DetailView
from users.models import UserAccount
from django.views.generic import TemplateView
from django.urls import reverse_lazy
from django.template.loader import render_to_string
from core.utils import generate_random_string
from django.core.mail import EmailMultiAlternatives
from django.contrib.sites.shortcuts import get_current_site


class LabSecView(LoginRequiredMixin, UserPassesTestMixin):
    def test_func(self):
        user = self.request.user
        if user.user_type == 'Lab_Sec':
            return True
        return False

class LabSecDashboardView(LabSecView, TemplateView):
    template_name = 'lab-secretaries/index.html'

templates/dashboard/users/students/add.html
{% extends 'base.html' %}
{% block title %}
    Add New Student
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="card shadow-sm">
            <div class="card-body">
                <h3 class="text-center py-3">Add Student</h3>
                <div class="col-md-10 mx-auto">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'partials/form.html' %}
                        <div class="py-3 text-center">
                            <button class="btn btn-primary">Add Student</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/dashboard/users/students/details.html
{% extends 'base.html' %} {% load static %} {% block title %} Student Details {% endblock %} {% block styles %}
<link href="{% static 'css/data-tables/dataTables.bootstrap4.min.css' %}" rel="stylesheet"> {% endblock %} {% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-4 p-3 text-center">
                        <div class="py-3">
                            <img src="{% static 'images/user/user_icon.png' %}" alt="{{ user.get_full_name }}" class="w-50">
                            <h5 class="pt-5">{{ user.get_full_name }}</h5>
                            <p class="text-muted">{{ user.get_user_type_display }}</p>
                            <p><span class="ti-time mx-1"> {{ user.date_joined | timesince}} ago
                                </span></p>
                            <p><span class="ti-mobile"> {{ user.phone_number}}
                                </span>
                                <p>
                                    <a href="" class="mx-1">
                                        <button class="btn btn-primary">Edit Student</button>
                                    </a>
                                </p>

                        </div>
                    </div>
                    <div class="col-md-8 ">
                        <div class="m-3 p-3 shadow-sm">
                            <h3 class="text-center py-3">Student Details</h3>
                            <div class="table-responsive">
                                <table class="table table-striped">
                                    <tbody>
                                        <tr>
                                            <th>Email</th>
                                            <td>{{ user.email }}</td>
                                        </tr>
                                        <tr>
                                            <th>Phone</th>
                                            <td>{{ user.phone_number }}</td>
                                        </tr>
                                        <tr>
                                            <th>Registration Number</th>
                                            <td>{{ user.registration_no }}</td>
                                        </tr>
                                        <tr>
                                            <th>Course</th>
                                            <td>{{ user.course }}</td>
                                        </tr>
                                        <tr>
                                            <th>Year of Study</th>
                                            <td>{{ user.year_of_study }}</td>
                                        </tr>
                                        <tr>
                                            <th>Gender</th>
                                            <td>{{ user.gender }}</td>
                                        </tr>
                                        <tr>
                                            <th>Status</th>
                                            <td>
                                                {% if user.is_active %}
                                                <span class="badge badge-pill badge-success">Active</span> {% else %}
                                                <span class="badge badge-pill badge-danger">Suspended</span> {% endif %}
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                                <div class="text-center py-3">
                                    {% if user.is_active%}
                                    <a href="{% url 'dashboard:student_confirm_suspension' user.pk %}" class="mx-1">
                                        <button class="btn btn-warning btn-md w-50">Suspend</button>
                                    </a>
                                    {% else %}
                                    <a href="{% url 'users:user_unsuspend_action' user.pk %}" class="mx-1">
                                        <button class="btn btn-success btn-md w-50">Activate</button>
                                    </a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-12 col-md-12">
        <div class="card equipment-allocations">
            <div class="card-header">
                <h5>All Equipment Allocations</h5>
            </div>

            <div class="card-block px-0 py-3">
                <div class="table-responsive">

                    <table class="table" id="data-table">
                        {% comment %}
                        <div class="float-right">
                            <a href="{% url 'equipment:equipment_add' %}" class="label theme-bg2 text-white f-12">Add
                                equipment</a>
                        </div> {% endcomment %}
                        <thead>
                            <tr>
                                <th> Serial No. </th>
                                <th> Equipment Type </th>
                                <th> Lab </th>
                                <th> Allocated By </th>
                                <th> Working Condition </th>
                                <th> Allocation Status </th>
                                <th> Date Added </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for allocation in equipment_allocations %}
                            <tr>
                                <td><a href="{% url 'equipment:equipment_details' allocation.equipment.id %}">{{ allocation.equipment.serial_no }}</a></td>
                                <td>{{ allocation.equipment.category.name }}</td>
                                <td>{{ allocation.equipment.lab.name }}</td>
                                <td><a href="{% url 'dashboard:lab_technician_details' allocation.allocated_by.id %}">{{ allocation.allocated_by }}</a>
                                </td>
                                {% if not allocation.equipment.is_damaged %}
                                <td> <span class="badge badge-pill badge-success">Working</span></td>
                                {% else %}
                                <td> <span class="badge badge-pill badge-danger">Damaged</span></td>
                                {% endif %} {% if allocation.is_returned %}
                                <td><span class="badge badge-pill badge-success">Returned</span></td>
                                {% else %}
                                <td><span class="badge badge-pill badge-danger">Unreturned</span></td>
                                {% endif %}
                                <td>{{ allocation.created_on }}</td>
                                <td><a href=" {% url 'equipment:allocation_details' allocation.pk %} " class="label theme-bg2 text-white f-12">View</a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %} {% block scripts %}
<script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script>
<script>
    $('#data-table').DataTable();
</script>
{% endblock %}

templates/dashboard/users/students/list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
All Students
{% endblock %}


{% block styles %}
<link href="{% static 'css/data-tables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="col-xl-12 col-md-12">
    <div class="card Recent-Users">
        <div class="card-header">
            <h5>All Students</h5>
        </div>
        <div class="card-block px-0 py-3">
            <div class="table-responsive">
                <table class="table" id="data-table">
                    <div class="float-right">
                        <a href="{% url 'dashboard:student_add' %}" class="label theme-bg2 text-white f-12">Add Student</a>
                    </div>
                    <thead>
                        <tr>
                            <th> Full Name </th>
                            <th> Gender </th>
                            <th> Contact </th>
                            <th> Registration No. </th>
                            <th> Course </th>
                            <th> Status </th>
                            <th> Date Joined </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for user in users %}
                        <tr>
                            <td>{{ user.get_full_name }}</td>
                            <td>{{ user.gender }}</td>
                            <td>{{ user.phone_number }}</td>
                            <td>{{ user.registration_no }}</td>
                            <td>{{ user.course }}</td>
                            {% if user.is_active %}
                            <td><span class="badge badge-pill badge-success">Active</span></td>
                            {% else %}
                            <td><span class="badge badge-pill badge-danger">Suspended</span></td>
                            {% endif %}
                            <td><i class="fas fa-circle text-c-green f-10 m-r-15"></i>{{ user.date_joined }}</td>
                            <td><a href="{% url 'dashboard:student_details' user.pk %}" class="label theme-bg2 text-white f-12">View</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock  %}

{% block scripts %}
<script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script>
<script>
    $('#data-table').DataTable();
</script>
{% endblock %}