equipment/urls.py
from django.urls import path

from .views.allocations import (AllocateToLecturerView, AllocateToStudentView,
                                AllocationCreateView, AllocationDetailView,
                                AllocationListView, AllocationUpdateView,
                                allocate_equipment, allocation_mark_as_damaged,
                                allocation_mark_as_fixed,
                                allocation_mark_as_lost,
                                allocation_mark_as_replaced, mark_as_returned,
                                unallocate_equipment)
from .views.batches import (BatchCreateView, BatchDetailView, BatchListView,
                            BatchUpdateView)
from .views.categories import (CategoryCreateView, CategoryDeleteView,
                               CategoryDetailView, CategoryListView,
                               CategoryUpdateView)
from .views.equipment import (EquipmentCreateView, EquipmentDeleteView,
                              EquipmentDetailView, EquipmentListView,
                              EquipmentUpdateView, mark_as_damaged,
                              mark_as_found, mark_as_lost, mark_as_out_service,
                              mark_as_working)
from .views.storage_units import (StorageUnitCreateView, StorageUnitDetailView,
                                  StorageUnitListView, StorageUnitUpdateView)
from .views.suppliers import (SupplierCreateView, SupplierDetailView,
                              SupplierListView, SupplierUpdateView)

app_name = "equipment"


urlpatterns = [
    # equipment category urls
    path('categories/',CategoryListView.as_view(),name="categories_list"),
    path('categories/add',CategoryCreateView.as_view(),name="category_add"),
    path('categories/<int:pk>/details',CategoryDetailView.as_view(),name="category_details"),
    path('categories/<int:pk>/edit',CategoryUpdateView.as_view(),name="category_edit"),
    path('categories/<int:pk>/delete',CategoryDeleteView.as_view(),name="category_delete"),

    # equipment batches urls
    path('batches/',BatchListView.as_view(),name="batch_list"),
    path('batches/add',BatchCreateView.as_view(),name="batch_add"),
    path('batches/<int:pk>/details',BatchDetailView.as_view(),name="batch_details"),
    path('batches/<int:pk>/edit',BatchUpdateView.as_view(),name="batch_edit"),

    #  equipment urls
    path('equipment/',EquipmentListView.as_view(),name="equipment_list"),
    path('equipment/add',EquipmentCreateView.as_view(),name="equipment_add"),
    path('equipment/<int:pk>/details',EquipmentDetailView.as_view(),name="equipment_details"),
    path('equipment/<int:pk>/edit',EquipmentUpdateView.as_view(),name="equipment_edit"),
    path('equipment/<int:pk>/delete',EquipmentDeleteView.as_view(),name="equipment_delete"),
    path('equipment/<int:pk>/mark-as-damaged/',mark_as_damaged,name="equipment_damaged_action"),
    path('equipment/<int:pk>/mark-as-working/',mark_as_working,name="equipment_working_action"),
    path('equipment/<int:pk>/mark-as-out-of-service/',mark_as_out_service,name="equipment_out_of_service_action"),
    path('equipment/<int:pk>/mark-as-lost/',mark_as_lost,name="equipment_lost_action"),
    path('equipment/<int:pk>/mark-as-found/',mark_as_found,name="equipment_found_action"),

    # supplier urls
    path('suppliers/', SupplierListView.as_view(), name='supplier_list'),
    path('suppliers/add/', SupplierCreateView.as_view(), name='supplier_add'),
    path('suppliers/<int:pk>/details/', SupplierDetailView.as_view(), name='supplier_details'),
    path('suppliers/<int:pk>/edit/', SupplierUpdateView.as_view(), name='supplier_edit'),

    # storage units
    path('storage-units/',StorageUnitListView.as_view(),name="storage_units_list"),
    path('storage-units/add',StorageUnitCreateView.as_view(),name="storage_unit_add"),
    path('storage-units/<int:pk>/details',StorageUnitDetailView.as_view(),name="storage_unit_details"),
    path('storage-units/<int:pk>/edit',StorageUnitUpdateView.as_view(),name="storage_unit_edit"),

    # allocations
    path('allocations/',AllocationListView.as_view(),name="all_allocations"),
    path('allocations/new/',AllocationCreateView.as_view(),name="new_allocation"),
    path('allocations/<int:pk>/details/',AllocationDetailView.as_view(),name="allocation_details"),
    path('allocations/<int:pk>/edit',AllocationUpdateView.as_view(),name="allocation_edit"),
    path('allocations/<int:pk>/mark-as-returned/', mark_as_returned, name="allocation_return_action"),
    path('allocations/<int:pk>/mark-as-damaged/', allocation_mark_as_damaged, name="allocation_damaged_action"),
    path('allocations/<int:pk>/mark-as-fixed/', allocation_mark_as_fixed, name="allocation_fixed_action"),
    path('allocations/<int:pk>/mark-as-lost/', allocation_mark_as_lost, name="allocation_lost_action"),
    path('allocations/<int:pk>/mark-as-replaced/', allocation_mark_as_replaced, name="allocation_replaced_action"),
    path('allocations/<int:pk>/allocate-to-student/', AllocateToStudentView.as_view(), name="allocate_to_student"),
    path('allocations/<int:pk>/allocate-to-lecturer/', AllocateToLecturerView.as_view(), name="allocate_to_lecturer"),
    path('allocations/<int:pk>/allocate/<int:user_pk>/', allocate_equipment, name="allocate_equipment_action"),
    path('allocations/<int:pk>/unallocate/<int:user_pk>/', unallocate_equipment, name="unallocate_equipment_action"),
]

scitlab/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView
from users.views.base import logout_user, login_redirect, LoginUserView, IndexTemplateView


urlpatterns = [
    # path('', IndexTemplateView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('accounts/',include('allauth.urls')),
    path('accounts/logout', logout_user, name='logout'),
    path('', LoginUserView.as_view(template_name='account/login.html'), name='login'),
    # path('', LoginView.as_view(template_name='account/login.html'),name='index'),
    path('accounts/login-redirect/', login_redirect, name='login_redirect'),
    path('dashboard/',include('dashboard.urls',namespace='dashboard')),
    path('users/',include('users.urls',namespace='users')),
    path('schools/',include('schools.urls',namespace='schools')),
    path('equipment/',include('equipment.urls',namespace='equipment')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path

from users.views.admin_actions import suspend_user, unsuspend_user
from users.views.lab_sec import LabSecDashboardView
from users.views.lab_technicians.equipment import (EquipmentCreateView,
                                                   EquipmentDetailView,
                                                   EquipmentListView,
                                                   EquipmentUpdateView,
                                                   StorageUnitDetailView,
                                                   StorageUnitListView,
                                                   StorageUnitCreateView)
from users.views.lab_technicians.index import LabTechnicianDashboardView
from users.views.students import StudentorLecturerDashboardView
from users.views.users.allocations import (AllocationDetailView,
                                           AllocationListView)

from .views.lab_technicians.allocations import (AllocateToLecturerView,
                                                AllocateToStudentView,
                                                AllocationCreateView,
                                                allocate_equipment)
from .views.lab_technicians.categories import (CategoryCreateView,
                                               CategoryDeleteView,
                                               CategoryDetailView,
                                               CategoryListView,
                                               CategoryUpdateView)
from .views.lab_technicians.lecturers import (LecturerDetailView,
                                              LecturerListView)
from .views.lab_technicians.students import StudentDetailView, StudentListView
from .views.lecturers import LecturerDashboardView
from .views.users.base import UserDetailView, UserProfileUpdateView

app_name = "users"

urlpatterns = [
    # lab technician url
    path('lab-technicians-dashboard/', LabTechnicianDashboardView.as_view(),
         name='lab_technicians_dashboard_index'),
    path('equipment/all/', EquipmentListView.as_view(), name="equipment_list"),
    path('equipment/add/', EquipmentCreateView.as_view(), name="equipment_add"),
    path('equipment/<int:pk>/details',
         EquipmentDetailView.as_view(), name="equipment_details"),
    path('equipment/<int:pk>/edit',
         EquipmentUpdateView.as_view(), name="equipment_edit"),
    path('storage-units/add', StorageUnitCreateView.as_view(),
         name="storage_unit_add"),
    path('storage-units/', StorageUnitListView.as_view(),
         name="storage_units_list"),
    path('storage-units/<int:pk>/details',
         StorageUnitDetailView.as_view(), name="storage_unit_details"),
    path('lab-technicians-dashboard/lecturers/all',
         LecturerListView.as_view(), name="lecturer_list"),
    path('lab-technicians-dashboard/lecturers/<int:pk>/details',
         LecturerDetailView.as_view(), name="lecturer_details"),
    path('lab-technicians-dashboard/students/all',
         StudentListView.as_view(), name="students_list"),
    path('lab-technicians-dashboard/students/<int:pk>/details',
         StudentDetailView.as_view(), name="student_details"),

    # allocations urls
    path('allocations/new/', AllocationCreateView.as_view(), name="new_allocation"),
    # lab secretary urls
    path('lab-secretaries-dashboard/', LabSecDashboardView.as_view(),
         name='lab_sec_dashboard_index'),

    # student dashboard
    path('student-dashboard/', StudentorLecturerDashboardView.as_view(),
         name="student_dashboard_index"),

    # lecturer
    path('lecturer-dashboard/', LecturerDashboardView.as_view(),
         name="lecturer_dashboard_index"),

    path('users/<int:pk>/suspend_user', suspend_user, name="user_suspend_action"),
    path('admin/admin/users/<int:pk>/unsuspend_user',
         unsuspend_user, name="user_unsuspend_action"),
    path('my-profile/', UserDetailView.as_view(), name="user_profile"),
    path('<int:pk>/profile-update/',
         UserProfileUpdateView.as_view(), name="profile_update"),

    # Allocation urls
    path('allocations/all/', AllocationListView.as_view(), name="allocations_list"),
    path('allocations/<int:pk>/details/',
         AllocationDetailView.as_view(), name="allocation_details"),
    path('allocations/<int:pk>/allocate-to-student/',
         AllocateToStudentView.as_view(), name="allocate_to_student"),
    path('allocations/<int:pk>/allocate-to-lecturer/',
         AllocateToLecturerView.as_view(), name="allocate_to_lecturer"),
    path('allocations/<int:pk>/allocate/<int:user_pk>/',
         allocate_equipment, name="allocate_equipment_action"),

    path('categories/', CategoryListView.as_view(), name="categories_list"),
    path('categories/add', CategoryCreateView.as_view(), name="category_add"),
    path('categories/<int:pk>/details',
         CategoryDetailView.as_view(), name="category_details"),
    path('categories/<int:pk>/edit',
         CategoryUpdateView.as_view(), name="category_edit"),
    path('categories/<int:pk>/delete',
         CategoryDeleteView.as_view(), name="category_delete"),
]

equipment/views.py
from django.shortcuts import render
from .models import Category, Equipment
from django.views.generic import CreateView, ListView, DetailView, UpdateView
from dashboard.views.dashboard import DashboardView



class CategoryCreateView(DashboardView, CreateView):
    model = Category
    fields = ("name")
    template_name = 'equipment/categories/add.html'


class CategoryListView(DashboardView, ListView):
    model = Category
    template_name = 'equipment/categories/list.html'
    context_object_name = 'categories'


class CategoryDetailView(DashboardView, DetailView):
    model = Category
    template_name = 'equipment/categories/details.html'
    context_object_name = 'category'

equipment/views/batches.py
from django.shortcuts import render
from django.contrib import messages
from ..models import Batch, Equipment
from django.views.generic import CreateView, ListView, DetailView, UpdateView
from dashboard.views.dashboard import DashboardView
from django.urls import reverse_lazy



class BatchCreateView(DashboardView, CreateView):
    model = Batch
    fields = ('category','supplier','serial_no','school','equipment_quantities')
    template_name = 'dashboard/equipment/batches/add.html'

    def get_success_url(self):
        messages.success(self.request,"Batch Added Successfully")
        return reverse_lazy('equipment:batch_details', kwargs={'pk':self.object.pk})


class BatchListView(DashboardView, ListView):
    model = Batch
    template_name = 'dashboard/equipment/batches/list.html'
    context_object_name = 'batches'


class BatchDetailView(DashboardView, DetailView):
    model = Batch
    template_name = 'dashboard/equipment/batches/details.html'
    context_object_name = 'batch'


class BatchUpdateView(DashboardView, UpdateView):
    model = Batch
    template_name = 'dashboard/equipment/batches/edit.html'
    fields = ('category','supplier', 'serial_no','school','equipment_quantities')

    def get_success_url(self):
        messages.success(self.request,"Batch Updated")
        return reverse_lazy('equipment:batch_details', kwargs={'pk':self.object.pk})

equipment/views/categories.py
from dashboard.views.dashboard import DashboardView
from django.contrib import messages
from django.db.models import Count
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)

from ..models import Batch, Category, Equipment


class CategoryCreateView(DashboardView, CreateView):
    model = Category
    fields = ('name',)
    template_name = 'dashboard/equipment/categories/add.html'

    def get_success_url(self):
        messages.success(self.request,"Category Added Successfully")
        return reverse_lazy('equipment:category_details', kwargs={'pk':self.object.pk})


class CategoryListView(DashboardView, ListView):
    model = Category
    template_name = 'dashboard/equipment/categories/list.html'
    context_object_name = 'categories'


class CategoryDetailView(DashboardView, DetailView):
    model = Category
    template_name = 'dashboard/equipment/categories/details.html'
    context_object_name = 'category'

    def get_context_data(self, **kwargs):
        category = self.object.id
        context = super().get_context_data(**kwargs)
        context["batches"] = Batch.objects.filter(category=category)
        context["equipments"] = Equipment.objects.filter(category=category)
        context["category"] = Category.objects.filter(id=category).annotate(category_batch_count=Count('batch')
            ).annotate(category_equipment_count=Count('equipment_category')).first()
        return context

class CategoryUpdateView(DashboardView, UpdateView):
    model = Category
    template_name = 'dashboard/equipment/categories/edit.html'
    fields = ('name',)

    def get_success_url(self):
        messages.success(self.request,"Category Updated")
        return reverse_lazy('equipment:category_details', kwargs={'pk':self.object.pk})

class CategoryDeleteView(DashboardView, DeleteView):
    model = Category
    context_object_name = 'category'
    template_name = 'dashboard/equipment/categories/delete.html'

    def get_success_url(self) -> str:
        messages.success(self.request, "Category Deleted Succefully")
        return reverse_lazy("equipment:categories_list")

equipment/views/storage_units.py
from django.shortcuts import render
from django.contrib import messages
from ..models import StorageUnit, Category, Equipment, Batch
from django.views.generic import CreateView, ListView, DetailView, UpdateView
from dashboard.views.dashboard import DashboardView
from django.urls import reverse_lazy
from django.db.models import Count


class StorageUnitCreateView(DashboardView, CreateView):
    model = StorageUnit
    fields = ('name','lab')
    template_name = 'dashboard/equipment/storage_units/add.html'

    def get_success_url(self):
        messages.success(self.request,"Storage Unit added")
        return reverse_lazy('equipment:storage_unit_details', kwargs={'pk':self.object.pk})


class StorageUnitListView(DashboardView, ListView):
    model = StorageUnit
    template_name = 'dashboard/equipment/storage_units/list.html'
    context_object_name = 'units'


class StorageUnitDetailView(DashboardView, DetailView):
    model = StorageUnit
    template_name = 'dashboard/equipment/storage_units/details.html'

    def get_context_data(self, **kwargs):
        unit = self.object.id
        context = super().get_context_data(**kwargs)
        context["equipments"] = Equipment.objects.filter(storage_unit=unit)
        context["unit"] = StorageUnit.objects.filter(id=unit).annotate(equipment_count=Count('equipment')).first()
        return context



class StorageUnitUpdateView(DashboardView, UpdateView):
    model = StorageUnit
    template_name = 'dashboard/equipment/storage_units/edit.html'
    fields = ('name','lab',)

    def get_success_url(self):
        messages.success(self.request,"Storage Unit updated")
        return reverse_lazy('equipment:storage_unit_details', kwargs={'pk':self.object.pk})

templates/users/equipment/add.html
{% extends 'base.html' %}
{% block title %}
    Add New Equipment
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="card shadow-sm">
            <div class="card-body">
                <h3 class="text-center py-3">Add Equipment</h3>
                <div class="col-md-10 mx-auto">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'partials/form.html' %}
                        <div class="py-3 text-center">
                            <button class="btn btn-primary">Add Equipment</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/users/equipment/details.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Equipment Details
{% endblock %}


{% block styles %}
<link href="{% static 'css/data-tables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12 ">
                        <div class="m-3 p-3 shadow-sm">
                            <h3 class="text-center py-3">Equipment Details</h3>
                            <div class="float-right d-flex">
                                {% if not equipment.is_allocated  and request.user.user_type == 'Lab_Tech' %}
                                <a href="{% url 'equipment:equipment_delete' equipment.pk %}" class="mx-1">
                                <button class="btn btn-md  btn-danger">Delete</button>
                                {% endif %}
                                 </a>
                            </div>
                            <div class="table-responsive">
                                <table class="table table-striped text-center">
                                    <tbody>
                                        <tr>
                                            <th>Name.</th>
                                            <td>{{ equipment.name }}</td>
                                        </tr>
                                        <tr>
                                            <th>Serial No.</th>
                                            <td>{{ equipment.serial_no }}</td>
                                        </tr>
                                        <tr>
                                            <th>Equipment Type</th>
                                            <td>{{ equipment.category.name }}</td>
                                        </tr>
                                        <tr>
                                            <th>Lab</th>
                                            <td>{{ equipment.lab.name }}</td>
                                        </tr>
                                        <tr>
                                            <th>Price</th>
                                            <td>{{ equipment.price }}</td>
                                        </tr>
                                        <tr>
                                            <th>Working Condition</th>
                                            {% if not equipment.is_damaged %}
                                            <td> <span class="badge badge-pill badge-success">Working</span></td>
                                            {% else %}
                                            <td> <span class="badge badge-pill badge-danger">Damaged</span></td>
                                            {% endif %}
                                        </tr>
                                        <tr>
                                            <th>Availability</th>
                                            {% if not equipment.has_exceeded_shelf_life %}
                                            <td> <span class="badge badge-pill badge-success">Yes</span></td>
                                            {% else %}
                                            <td> <span class="badge badge-pill badge-danger">Out of Service</span></td>
                                            {% endif %}
                                        </tr>
                                        <tr>
                                            <th>Allocation Status</th>
                                            {% if equipment.is_allocated  %}
                                            <td> <span class="badge badge-pill badge-info">Allocated</span></td>
                                            {% else %}
                                            <td> <span class="badge badge-pill badge-success">In Storage</span></td>
                                            {% endif %}
                                        </tr>
                                        <tr>
                                            <th>Added On</th>
                                            <td>{{ equipment.created_on }}</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        {% if request.user.user_type == 'Lab_Tech' or request.user.user_type == 'Staff' %}
                        <div class="row text-center">
                         <div class="col-md-6">
                            <a href="{% url 'users:equipment_edit' equipment.pk %}" class="mx-1 col-md-6">
                                <button class="btn btn-sm w-50 btn-primary">Edit</button>
                            </a>
                         </div>
                         <div class="col-md-6">
                            {% if equipment.is_damaged == False %}
                            <a href="{% url 'equipment:equipment_damaged_action' pk=equipment.pk %}" class="mx-1 col-md-6">
                                <button class="btn btn-sm w-50 btn-warning">Mark as Damaged</button>
                            </a>
                            {% else %}
                            <a href="{% url 'equipment:equipment_working_action' pk=equipment.pk %}" class="mx-1 col-md-6">
                                <button class="btn btn-sm w-50 btn-success">Mark as Working</button>
                            </a>
                            {% endif %}
                            {% if equipment.has_exceeded_shelf_life == False %}
                                <a href="{% url 'equipment:equipment_out_of_service_action' pk=equipment.pk %}"
                                    class="mx-1 col-md-3 mx-auto">
                                    <button class="btn btn-sm w-50 btn-warning">Mark as Out Of Service</button>
                                </a>
                            {% endif %}
                         </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
       
    </div>
</div>
    
    </div>
</div>

{% endblock  %}

{% block scripts %}
<script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script>
<script>
    $('#data-table').DataTable();
</script>
{% endblock %}

templates/users/equipment/edit.html
{% extends 'base.html' %}
{% block title %}
    Edit Equipment
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="card shadow-sm">
            <div class="card-body">
                <h3 class="text-center py-3">Edit Equipment</h3>
                <div class="col-md-10 mx-auto">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'partials/form.html' %}
                        <div class="py-3 text-center">
                            <button class="btn btn-primary">Save Changes</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/users/equipment/list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
All Equipment
{% endblock %}


{% block styles %}
<link href="{% static 'css/data-tables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="col-xl-12 col-md-12">
    <div class="card Recent-equipments">
        <div class="card-header">
            <h5>All Equipment</h5>
            {% if equipments.count > 0 %}
            <div class="float-right">
                <button class="btn btn-info" id="printBtn" value="ExportToPdf" onclick="ExportToPdf()"><span
                        class="pcoded-micon"><i class="feather icon-printer"></i></span> Print</button>
            </div>
            {% endif %}
        </div>

        <div class="card-block px-0 py-3">
            <div class="table-responsive">
                <table class="table" id="data-table" style="background-color: #fff;">
                    <div class="float-right">
                        <a href="{% url 'users:equipment_add' %}" class="label theme-bg2 text-white f-12">Add
                            equipment</a>
                    </div>
                    <div class="content" id="EquipmentTable" >
                        <thead>
                            <tr>
                                <th> Serial No. </th>
                                <th> Equipment Name </th>
                                <th> Lab </th>
                                <th> Storage Unit </th>
                                <th> Allocation Status</th>
                                <th> Working Condition </th>
                                <th> Date Added </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for equipment in equipments %}
                            <tr>
                                <td>{{ equipment.serial_no }}</td>
                                <td>{{ equipment.name }}</td>
                                <td>{{ equipment.lab.name }}</td>
                                <td>{{ equipment.storage_unit.name }}</td>
                                {% if not equipment.is_allocated %}
                                <td><span class="badge badge-pill badge-success">In Storage</span></td>
                                {% else %}
                                <td><span class="badge badge-pill badge-danger">Allocated</span></td>
                                {% endif %}
                                {% if equipment.is_damaged == False %}
                                <td> <span class="badge badge-pill badge-success">Working</span></td>
                                {% else %}
                                <td> <span class="badge badge-pill badge-danger">Damaged</span></td>
                                {% endif %}
                                <td>{{ equipment.created_on }}</td>
                                <td><a href=" {% url 'users:equipment_details' equipment.pk %} "
                                        class="label theme-bg2 text-white f-12">View</a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </div>

                </table>
            </div>
        </div>
    </div>
</div>
{% endblock  %}

{% block scripts %}
<script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script>
<script>
    $(document).ready(function () {
        $('#data-table').DataTable({
            "pageLength": 25,
        });
    });

    function ExportToPdf() {
        const pdfTitle = '{{ request.user.lab.name }} Equipment'
        console.log(pdfTitle)
        const pdf = new jsPDF('p', 'pt', 'a4');
        pdf.addHTML($('.table'), function () {
            if (pdfTitle) {
                pdf.save(`${pdfTitle}.pdf`);
            } else {
                pdf.save('Equipment.pdf');
            }
        });
    }
</script>
{% endblock %}